services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm_tracebility:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=http://qdrant:6333
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=trace_db
      - POSTGRES_USER=trace_user
      - POSTGRES_PASSWORD=trace_pass
    depends_on:
      - qdrant
      - postgres

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: trace_db
      POSTGRES_USER: trace_user
      POSTGRES_PASSWORD: trace_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@trace.io
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  qdrant_data:
  ollama_data:
  postgres_data: